# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.CharField(blank=True, max_length=120, null=True)),
                ('match_at', models.DateTimeField(blank=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rest_ex.Games')),
            ],
        ),
    ]
