# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('error', models.CharField(blank=True, max_length=120, null=True)),
                ('small_league', models.CharField(blank=True, max_length=120, null=True)),
                ('grand_league', models.CharField(blank=True, max_length=120, null=True)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rest_ex.Matches')),
            ],
        ),
    ]
