# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_ex', '0002_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
